#!/bin/bash

cd "`dirname $0.`/.."

TESTS=( "file_utils" "runtime_config" "commandline" "query_string" "geometry_math" "serve" "cache")

PASSED=0
FAILED=0

run_test() {
	test/$1
	if [ $? == 0 ]; then
		let PASSED=$PASSED+1
	else
		let FAILED=$FAILED+1
	fi
}

run_all() {
	for TEST in ${TESTS[@]}; do
		run_test $TEST
		echo ""
	done

	echo "Tests passed: $PASSED failed: $FAILED"
}


time run_all

if [ $FAILED != 0 ]; then
	exit 1
fi