#!/bin/bash

cd "`dirname $0.`/.."

TESTS=( "file_utils" "runtime_config" "commandline" "query_string" "geometry_math" "serve" "cache"  "scaler" "main" )

PASSED=0
FAILED=0

run_test() {
	test/$1
	if [ $? == 0 ]; then
		let PASSED=$PASSED+1
	else
		let FAILED=$FAILED+1
	fi
}

run_all() {
	echo "=== Running Unit tests:"
	for TEST in ${TESTS[@]}; do
		run_test test_$TEST
		echo ""
	done

	echo "== Unit test summary:"
	echo "Tests suits passed: $PASSED failed: $FAILED"
}


time run_all

if [ $FAILED != 0 ]; then
	exit 1
fi
